/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface PwcTabview {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLPwcTabviewElement extends Components.PwcTabview, HTMLStencilElement {}
  var HTMLPwcTabviewElement: {
    prototype: HTMLPwcTabviewElement;
    new (): HTMLPwcTabviewElement;
  };
  interface HTMLElementTagNameMap {
    'pwc-tabview': HTMLPwcTabviewElement;
  }
}

declare namespace LocalJSX {
  interface PwcTabview {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'pwc-tabview': PwcTabview;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'pwc-tabview': LocalJSX.PwcTabview & JSXBase.HTMLAttributes<HTMLPwcTabviewElement>;
    }
  }
}


